# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, thanks for trying this out!
  AWS_PROFILE: qa # <--- REPLACE WITH WHATEVER YOU WANT TO RUN AGAINST

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  init:
    cmds:
      - go get
      - go mod tidy
    dir: v1
  run:
    cmds:
      - go run main.go -profile qa
    dir: v1
